### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by DataBot3000** [DataBot3000/BlockChain#1]
Traceback (most recent call last):

  File "<ipython-input-4-f9cf90129986>", line 45, in <module>
    blockchain = [create_genesis_block()]

  File "<ipython-input-4-f9cf90129986>", line 32, in create_genesis_block
    return Block(0, date.datetime.now(), "Gensis Block", "0")

  File "<ipython-input-4-f9cf90129986>", line 17, in __init__
    self.hash = self.hash_block()

  File "<ipython-input-4-f9cf90129986>", line 24, in hash_block
    str(self.previous_hash))

TypeError: Unicode-objects must be encoded before hashing

**Comment by DataBot3000** [comment]
Potentially need to specify an encoding when using hashlib. Taken from [stackoverflow](https://stackoverflow.com/questions/7585307/how-to-correct-typeerror-unicode-objects-must-be-encoded-before-hashing): 
>>> import hashlib
>>> hashlib.sha256(str(random.getrandbits(256)).encode('utf-8')).hexdigest()
'cd183a211ed2434eac4f31b317c573c50e6c24e3a28b82ddcb0bf8bedf387a9f'

**Comment by DataBot3000** [comment]
```
  def hash_block(self):
    sha = hasher.sha256()
    sha.update((str(self.index) + 
    str(self.timestamp) + 
    str(self.data) + 
    str(self.previous_hash)).encode()) #change here
    return sha.hexdigest()
```

issue was resolved by adding `.encoded())`
